package backend;

import org.mindrot.jbcrypt.BCrypt;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Patient {
    //variables
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    int PatientID;      //generated by backend
    String FirstName;   //Required
    String LastName;    //Required
    String Gender;      //Optional
    String DOB;         //Required
    String Phone;       //Required
    String Email;       //Optional
    String Pass;        //Required
    String AdmissionDate; //Set by functions
    String LeaveDate;     //Set by functions
    String LastUpdated;    //Set by functions
    Integer RoomID;     //Set Later
    //empty constructor
    public Patient() { }
    //constructor with required fields
    public Patient(String fn, String ln, String dob, String p, String pass) {
        FirstName = fn; //set first name
        LastName = ln; //set last name
        DOB = dob; //set dob
        Phone = p;  //set phone number
        RoomID = null; //no room at the start

        //hashing!
        Pass = BCrypt.hashpw(pass, BCrypt.gensalt());
    }
    //constructors with optional fields variations
    public Patient(String fn, String ln, String g, String dob, String p, String e, String pass) {
        FirstName = fn; //set first name
        LastName = ln; //set last name
        Gender = g;
        DOB = dob; //set dob
        Phone = p;  //set phone number
        Email = e;
        RoomID = null; //no room at the start

        //hashing!
        Pass = BCrypt.hashpw(pass, BCrypt.gensalt());
    }
    //getters and setters for later types
    public void addPhone(String p){
        Phone = p;
    }
    public void addGender(String g){
        Gender = g;
    }
    public int getPatientID() {
        return PatientID;
    }
    public void setPatientID(int patID) {
        PatientID = patID;
    }
    public String getPass() {
        return Pass;
    }
}
